name: pydart
publish_to: none
description: The flutter.dev website rebuilt in Flutter.
version: 2.0.5

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  animations: ^2.0.11
  url_launcher: ^6.3.0
  video_player: ^2.9.1
  webview_flutter: ^4.9.0
  webview_flutter_web: ^0.2.3+2
  universal_html: ^2.2.4
  google_fonts: ^6.2.1
  universal_io: ^2.2.2
  responsive_framework: ^1.5.1
  rxdart: ^0.28.0
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  flutter_svg: ^2.0.17
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  firebase_analytics: ^11.4.2
  flutter_image_compress: ^2.4.0
  
  connectivity_plus: ^6.1.3
  go_router: ^14.8.0
  intl: ^0.20.2
  dotted_border: ^2.1.0
  lottie: ^3.3.1
  font_awesome_flutter: ^10.8.0
  url_strategy: ^0.3.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  http: ^1.3.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  rive: ^0.13.20
  file_picker: ^9.0.2
  flutter_animate: ^4.5.2
  visibility_detector: ^0.4.0+2
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.4.1
  phosphor_flutter: ^2.1.0
  simple_animations: ^5.2.0
  supercharged: ^2.1.1
#  responsive_framework:
#    path: responsive_framework/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/embedded/
    - assets/images/insights/
    - assets/images/others/
    - assets/images/services/
    - assets/images/team/
    - assets/images/career/
    - assets/images/home/
    
    - assets/frames/
    - assets/logos/
    - assets/logos/insights/
    - assets/videos/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/product_sans_regular.ttf
        - asset: assets/fonts/product_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/product_sans_italic.ttf
          style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf


    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_italic.ttf
          style: italic
