name: Build & Deploy Flutter Web to Firebase

on:
  push:
    branches:
      - main     # or whichever branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web Release
        run: flutter build web --release

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy -P pydart-india
